### ISSUE TITLE
RecyclerView in PlantListFragment does not maintain scroll position on screen rotation

### ISSUE THREAD

**Issue by chris-feldman** [googlesamples/android-sunflower#10]
I think this is is because the adapter is initialized and set in the onCreateView, which is called on each rotation. 

The scroll position is restored if you set the adapter in subscribeUi instead of in the onCreateView, but then you get a console error:

> 05-30 16:58:03.796 4570-4570/com.google.samples.apps.sunflower E/RecyclerView: No adapter attached; skipping layout

**Comment by tiembo** [comment]
Thanks for reporting this!

**Comment by tiembo** [comment]
Fixed via #33
