### ISSUE TITLE
Suggestions: clicking effect on plant-list, and transition of image from it to plant-details

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-sunflower#102]
There is no clicking effect when pressing on the plant. I suggest to add it.

Also, I suggest to have a transition of the image fro the list to the plant-details screen.

**Comment by XinyueZ** [comment]
I think the #75 should be done first before this.

**Comment by AndroidDeveloperLB** [comment]
It says it has 2 toolbars, but I don't see it (when launching).
Is it behind the scenes, in code?

**Comment by AndroidDeveloperLB** [comment]
It's just a suggestion...

**Comment by andhie** [comment]
i have reported both as issue #66, click effect is related to issue #64

**Comment by AndroidDeveloperLB** [comment]
OK sorry
