### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aztek-god** [googlesamples/android-sunflower#12]
Why do you use your own singleton implementation when you can use embedded language construction: object?

**Comment by tiembo** [comment]
The singletons in this project follow the pattern established in the [Architecture Components project](https://github.com/googlesamples/android-architecture-components).  Here is an [example](https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSampleKotlin/app/src/main/java/com/example/android/observability/persistence/UsersDatabase.kt) of its use, and the [pull request](https://github.com/googlesamples/android-architecture-components/pull/125) with more context.
