### ISSUE TITLE
PlantDetailFragmentTest failed: "java.lang.IllegalArgumentException"

### ISSUE THREAD

**Issue by williamwue** [googlesamples/android-sunflower#122]
When I run androidTest, it would be failed in testShareTextIntent of PlantDetailFragmentTest.
Log:

> java.lang.IllegalArgumentException: Required argument "plantId" is missing and does not have an android:defaultValue
> at com.google.samples.apps.sunflower.PlantDetailFragmentArgs.fromBundle(PlantDetailFragmentArgs.java:23)
> at com.google.samples.apps.sunflower.PlantDetailFragment.onCreateView(PlantDetailFragment.kt:51)
> at android.support.v4.app.Fragment.performCreateView(Fragment.java:2425)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> at android.support.v4.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2644)
> at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2415)
> at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2371)
> at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272)
> at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> at android.os.Handler.handleCallback(Handler.java:754)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:163)
> at android.app.ActivityThread.main(ActivityThread.java:6348)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
> 
> Test running failed: Instrumentation run failed due to 'Process crashed.'

**Comment by tiembo** [comment]
Thanks for the report!
