### ISSUE TITLE
databinding has been declared in gradle but never used.

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-sunflower#13]
I am not sure whether forget or is not needed.
I still see some "findViewById" in this project.

**Comment by aztek-god** [comment]
There is no findViewById because instead it "kotlin-android-extensions" is used. This plugin allows you to type an id of view element right in activity/fragment.

**Comment by XinyueZ** [comment]
@aztek-god GardenFragment there are some. I have created a [pr](https://github.com/googlesamples/android-sunflower/pull/14) to optimize these.

**Comment by tiembo** [comment]
Data binding is used in the project, such as in `PlantDetailFragment` and in binding adapters.
