### ISSUE TITLE
Fix resolving strings in ViewModel

### ISSUE THREAD

**Issue by karczews** [googlesamples/android-sunflower#132]
ViewModel should not be resolving strings from resources as shown in 
https://github.com/googlesamples/android-sunflower/blob/4c8d9045d9662e5c659c9ee3dafc66d993e28968/app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantAndGardenPlantingsViewModel.kt

If user changes locale on device, activity/fragment will be recreated but ViewModel will be retained with data, that might be invalid for new configuration/locale. Because this is sample referenced by official google documentation, it should not be showcasing invalid ViewModel usage. 

> The Sunflower demo app demonstrates best practices with architecture components.
https://developer.android.com/topic/libraries/architecture/

ref. https://issuetracker.google.com/u/1/issues/111961971

**Comment by andhie** [comment]
its true it improper to do this. in fact should not pass in a `Context` inside a `ViewModel` but a `AndroidViewModel`. it would be even better if its android framework free to be easily testable.

Usually my approach would be writing it in XML databinding
`android:text="@{@string/watering_next_prefix(viewModel.waterDateString)}"`

**Comment by XinyueZ** [comment]
Hey @andhie @karczews , see https://github.com/googlesamples/android-sunflower/pull/135
