### ISSUE TITLE
video tutorials or walkthrough for the app?

### ISSUE THREAD

**Issue by touseefbsb** [googlesamples/android-sunflower#133]
Hi! First of all great work with the app and showcasing best practices of latest android jetpack and stuff. Secondly I have been trying to find a proper end to end tutorial or walkthrough online which makes a complete app using all or atleast major components of android jetpack, because I am a beginner in android development and instead of wasting my time on older standards (before io 18 )  I am trying to start my learning process with new standards like kotlin, jetpack, ktx, constraint layout 2.0 etc. So I came across this repo which seems to be almost wht I was looking for, only missing part is step by step walkthrouh or tutorials to make the app, I know it is too much to ask, but it is just a suggestion. Thanks for the repo anyways :)

**Comment by clucle** [comment]
+1

**Comment by tiembo** [comment]
Hi there - thanks for the suggestion.  Many of the components used in Sunflower have standalone tutorials, which are available at https://codelabs.developers.google.com/?cat=Android.

There are currently no plans to create a Sunflower specific tutorial.
