### ISSUE TITLE
Converting findviewbyid into databinding for Fragment

### ISSUE THREAD

**Issue by bhaarn** [googlesamples/android-sunflower#142]
Hi,

We can change all the findviewbyid logic to databinding as we are following MVVM architecture and we had already <layout> tag in the fragment xmls.

**Comment by bhaarn** [comment]
I have the code but don't know the process of code inspection.  That's why I had not pushed the changes.

**Comment by XinyueZ** [comment]
duped in #25 #14, I will merge *new* changes from the master so long it's updated.

**Comment by tiembo** [comment]
Addressed by #162
