### ISSUE TITLE
Navigation and bottom navi view

### ISSUE THREAD

**Issue by candrwow** [googlesamples/android-sunflower#143]
Hello,before I use 
` implementation "android.arch.navigation:navigation-fragment:1.0.0-alpha03"
    implementation "android.arch.navigation:navigation-ui:1.0.0-alpha03"`
there is no problem,today I change to alpha04,so I meet a problem,I don't know it's an bug or I use way not right.
MainActivity use navi and bottom navi view,like below code,it contains 5 fragments,eg:ABCDE,when I switch from A to B,then switch from B to C,D or E,now I click android system <- back button,fragment change to A,but bottom navi view's tab still last one:C,D or E.I don't change code In addition to change library version outside.

`supportFragmentManager = getSupportFragmentManager();
        navHostFragment = (NavHostFragment) supportFragmentManager.findFragmentById(R.id.frag_nav);
        navController = navHostFragment.getNavController();
        NavigationUI.setupWithNavController(navigation, navController);`

**Comment by tiembo** [comment]
For problems using the navigation library, please open an issue in the Google Issue Tracker in the Navigation component: https://issuetracker.google.com/issues?q=componentid:409828
