### ISSUE TITLE
Implement display cutout

### ISSUE THREAD

**Issue by tiembo** [googlesamples/android-sunflower#163]
https://developer.android.com/guide/topics/display-cutout/

**Comment by XinyueZ** [comment]
I think for this app the cutout feature is meaningful only when the app is running with the landscape orientation.

**Comment by XinyueZ** [comment]
Actually, I have a potential PR for this ticket.

In order to support **cutout** feature and let users know, the app should be best in **fullscreen** mode, otherwise, people must write codes instead just style-files changing (api 28). Can we commitment that the app will be switched to fullscreen?

**Comment by tiembo** [comment]
Per the [fullscreen guidelines](https://developer.android.com/training/system-ui/immersive), Sunflower isn't a good candidate to run in fullscreen mode.

**Comment by XinyueZ** [comment]
OK, I'll remove Line 22-23, 26-27 in the PR #173 
https://github.com/XinyueZ/android-sunflower/blob/feature/display-cutout/app/src/main/res/values-v28/styles.xml#L23
However, the Cut-Out will effect system status-bar and independent from app's toolbar.

**Is this acceptable?** 
![screenshot_1537130119](https://user-images.githubusercontent.com/7869833/45600706-59418580-ba01-11e8-8b05-28cfb7ea1e5d.png)

**Comment by nic0lette** [comment]
Given that Sunflower is not full screen, and doesn't render anything into the status bar, and given that the default behavior is for the status bar to extend to at least the height of the cut-out, it feels like we should just close this issue.

Thoughts? @tiembo @XinyueZ

**Comment by tiembo** [comment]
Agreed - the default system behavior appropriate.  As Sunflower grows, we can revisit customizing cutout usage if a good use case arises.

**Comment by XinyueZ** [comment]
totally agree
