### ISSUE TITLE
In rootProject build.gradle file, the maven repository needs to be above the jcenter one otherwise will error out as time-out/cannot find version

### ISSUE THREAD

**Issue by billyji32** [googlesamples/android-sunflower#188]
repositories {
        maven { url 'http://dl.bintray.com/kotlin/kotlin-eap' }
        google()
        jcenter()
    }

**Comment by tiembo** [comment]
I'm unable to reproduce this error locally or via CI.  Can you try again?  Sometimes the repos have hiccups

**Comment by billyji32** [comment]
You're right, I cleared my cache and still cannot reproduce the error.
