### ISSUE TITLE
com.google.samples.apps.sunflower.databinding.ActivityGardenBinding : Unresolved reference

### ISSUE THREAD

**Issue by VitaFitSoft** [googlesamples/android-sunflower#189]
I am using Android Studio 3.3 Canary 10 and having trouble correcting the Unresolved reference error for the missing package databinding and class ActivityGardenBinding in latest Github download. I download the example app twice but cannot find the package and class mentioned.
Is there a reason for this? or am I doing something wrong.

**Comment by XinyueZ** [comment]
U should now use 11

**Comment by VitaFitSoft** [comment]
I downloaded the latest version of Sunflower using Canary 11 as advised and getting no more unresolved errors,  but I need to address 2 things.
1. How to update Kotlin plugin in the IDE to 1.3-m2 to match the current project gradle implementation.
2. How to address the warning message "API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

Thank you

**Comment by XinyueZ** [comment]
Hi @VitaFitSoft 
1. Just https://plugins.jetbrains.com/plugin/6954-kotlin, take one of them EAP-NEXT or ideadev for your version.
2. The bug is because that Kotlin uses some deprecated APIs, It doesn't matter at moment to build app.
https://issuetracker.google.com/issues/116253412

**Comment by tiembo** [comment]
Hi @VitaFitSoft - I haven't tested Sunflower against the Android Studio 3.3 canaries, but it works fine on Android Studio 3.2.

The latest Kotlin plugin change (#192) was merged recently.  Give that a try?

**Comment by VitaFitSoft** [comment]
Hi Tiem,

I have tried it on Studio 3.3 Canaries and it seems to be working fine at the moment


cheers



Owen

________________________________
