### ISSUE TITLE
Why not data-binding in GardenPlantingAdapter?

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-sunflower#20]
I see still there are some `findViewById` calls and use `non-data-binding` style.
Is that the contract of this project that `data-binding` would not be used in list-view like objects?
I want a confirm, otherwise I will try a PR to optimize it with `data-binding`.

**Comment by tiembo** [comment]
Yes, the adapters should also use data binding.  That'd be great if you could open a PR for data binding in `GardenPlantingAdapter`.
