### ISSUE TITLE
No enum constant com.android.manifmerger.AttributeOperationType.TARGETAPI

### ISSUE THREAD

**Issue by yorkwang** [googlesamples/android-sunflower#213]
Just tried 
    compile "android.arch.work:work-runtime:1.0.0-alpha09",  error "No enum constant com.android.manifmerger.AttributeOperationType.TARGETAPI" will be shown. But  compile "android.arch.work:work-runtime:1.0.0-alpha06" will compile successfully.

**Comment by tiembo** [comment]
Hi @yorkwang - are you still running into this issue?

**Comment by yorkwang** [comment]
Yes, I have to use "android.arch.work:work-runtime:1.0.0-alpha06" instead, my project used gradle:2.2.3, that might be the reason.

**Comment by tiembo** [comment]
I recommend trying with the latest versions of Work Manager and Gradle, as there have been breaking API changes and improvements.
