### ISSUE TITLE
Turkish Special Characters

### ISSUE THREAD

**Issue by MuratTopcu** [googlesamples/android-sunflower#216]
If the language of Windows is Turkish, when I try to compile the software, Turkish characters are incorrect
https://en.wikipedia.org/wiki/Wikipedia:Turkish_characters
![ekran alintisi](https://user-images.githubusercontent.com/2551727/46489445-13acf700-c80e-11e8-867c-1798ee21d3b0.PNG)

**Comment by tiembo** [comment]
This does not look like an issue with the Sunflower code, as the Binding files are auto-generated.  I would suggest reporting a bug in the [Android public tracker](https://issuetracker.google.com/issues/new?component=190923&template=841312).
