### ISSUE TITLE
Toolbar navigationIcon change

### ISSUE THREAD

**Issue by Vicent9920** [googlesamples/android-sunflower#245]
Is the icon switch around Toolbar automatically set? Why are there no relevant code found in Activity and Fragment?
`
请问 Toolbar 左右图标切换是自动设置的吗？为什么在 Activity 和 Fragment 里面没有发现相关代码？
`

**Comment by XinyueZ** [comment]
Because nav-lib

**Comment by tiembo** [comment]
Yes, the icon change functionality is part of the support libraries.
