### ISSUE TITLE
Getting Started Description Suggested Improvement

### ISSUE THREAD

**Issue by labermt** [googlesamples/android-sunflower#248]
New to Android (okay, I was here almost 10 years ago, but I had to leave for a while... ) 

I see I have to run gradlew to build the app, but I have no idea how to run it. The Getting Started isn't clear. Probably something I should know, but I don't. 

Can you improve the steps on how to see the app work?

**Comment by XinyueZ** [comment]
./gradlew build

**Comment by tentenponce** [comment]
@labermt to assemble app:

`./gradlew assembleDebug`

for installing it directly on emulator or on connected device:

`./gradlew installDebug`

You could find even more detailed info about this [here](https://developer.android.com/studio/build/building-cmdline)

**Comment by tiembo** [comment]
Thanks everyone for the responses.  For general tips on building and running an app, check out https://developer.android.com/studio/run/.

@labermt feel free to open a pull request for improving instructions.

**Comment by tiembo** [comment]
Updated the README with more instructions on getting started.
