### ISSUE TITLE
hi,can you tell me  ImageDecoder when to support the api under Android P? thank you 

### ISSUE THREAD

**Issue by jhyHenry** [googlesamples/android-sunflower#259]

**Comment by tiembo** [comment]
This issue tracker is to log bugs and feature requests for this project.  For help with ImageDecoder, please look at the docs - [US website](https://developer.android.com/reference/android/graphics/ImageDecoder), [Chinese website](https://developer.android.google.cn/reference/android/graphics/ImageDecoder)
