### ISSUE TITLE
Implement 1.0.0-alpha12 of workmanager (breaking changes !!)

### ISSUE THREAD

**Issue by RoarGronmo** [googlesamples/android-sunflower#260]
There are some breaking changes in 1.0.0-alpha12 of workmanager, see here: 
<snip start>
Breaking API Changes

Support for Firebase JobDispatcher has been removed because of its impending deprecation. This means that the work-firebase artifact will no longer be updated as we head into beta. We will be looking into adding an alternative in the future.

Combined Payload into Result. Result is now a "sealed class" with three concrete implementations, which you can obtain via Result.success() (or Result.success(Data)), Result.failure() (or Result.failure(Data)), and Result.retry(). Your ListenableFutures now result Result instead of Payload. Workers don't have getter and setter methods for output Data.

Added Operation.await() and ListenableFuture.await() Kotlin extension methods.

Renamed Operation.getException() to Operation.getThrowable().

The ContentUriTriggers class and methods referencing it are no longer available for public usage.
Removed the rest of the varargs methods in WorkManager, WorkContinuation, and OneTimeWorkRequest to streamline the API. To fix any build problems, you can wrap your existing varargs with Arrays.asList(...). We still include single-argument versions of each method.

Removed WorkContinuation.combine(OneTimeWorkRequest, *) variants. They were presenting a confusing API; the existing combine methods are more understandable.

<snip end>

At least for Result, this makes problem for many...

RG

**Comment by tiembo** [comment]
Thanks for opening the issue.  PR #263 addresses the breaking changes and uses the new API calls.
