### ISSUE TITLE
So how this jetpack sample makes our life easier?

### ISSUE THREAD

**Issue by anonym24** [googlesamples/android-sunflower#299]
> The Sunflower demo app uses many different Jetpack components to demonstrate Android development best practices

Great but the result app is quite simple, though its source code..

I'm trying to learn about Jetpack/AndroidX but at first glance this project looks quite difficult to me. Many classes, quite unreadable for such simple app. Is this really makes our projects smaller? Also using this technology seems we have to use more different annotations in the code

If I was a total newbie in Android but knew Java or Kotlin quite enough it would be much easier to understand implementation of this app without Jetpack but using standard Android API and MVC model, old RecyclerView and so on

![image](https://user-images.githubusercontent.com/8851301/50736712-690bf200-11c9-11e9-8e4f-cd743fea2004.png)

>  uses many different Jetpack components 

Mb I'll try to learn each component separately (some tutorials from the internet) and mb then it will become easier

**Comment by anonym24** [comment]
And this one is weird https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0 from https://developer.android.com/topic/libraries/architecture/

Why is it in Java?

![screenshot_3](https://user-images.githubusercontent.com/8851301/50738174-e2abdc00-11d9-11e9-9fb7-7b49c0d9ffd7.png)

Also this Flutter + Dart language which syntax looks even older than Java's when it's 2019 and we have Kotlin/Swift...

It becomes even crazier:)

**Comment by Zhuinden** [comment]
Hmm maybe I should copy this example over to me :wink:

**Comment by Zhuinden** [comment]
@anonym24 you can also see the Kotlin version of the codelabs: https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#0
