### ISSUE TITLE
 Attribute application@appComponentFactory Conficts ?

### ISSUE THREAD

**Issue by kuno** [googlesamples/android-sunflower#340]
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:24:5-40:19 to override.
```

I pulled the last code at  commit 7fe07770fd04918e2e2ca2a5ac32ece24bf97402, but failed to build on AS 3.3.1 on my laptop. Is this normal ?

**Comment by XinyueZ** [comment]
I do not have this problem in my AS 331.
However, to the problem it self, you can try to add `      android:appComponentFactory="placeholder"` to the `<application>`, it might help you.

**Comment by kuno** [comment]
@XinyueZ 

This is wired to me as well. Since this piece of code running normally on AS 311 on my other laptop.

Can someone confirm me that this's possible to put `android.support.v4` and `androidx.core` artifacts side by side in an Android project?

**Comment by XinyueZ** [comment]
The project is AndroiX enabled, as I know it is the sample/demo of jetpack, there's no need to use support namespaces.
I am so glad to see some details of your problem, maybe can help you to solve.

**Comment by kuno** [comment]
I think it's not about code but AS, I just create a project in AS from scratch:

with gradle.properties
```
android.useAndroidX=false
android.enableJetifier=false
```
and 
```gradle
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
```
But the edior can not found `android.support.v7.app.AppCompatActivity` instead `androidx.appcompat.app.AppCompatActivity`
![hilton-android____works_github_kuno_hilton-android__-_____demo_src_main_java_com_wiredcraft_hilton_honor_mainactivity_kt__demo_](https://user-images.githubusercontent.com/161327/53003339-b5557d80-3469-11e9-8267-b1728430ff69.png)

**Comment by kuno** [comment]
My fault, it turns out that my two laptops have different global Gradle settings, one turned androidx on, another off.

Thanks for reply, anyway.

**Comment by mkamals** [comment]
> @XinyueZ
> 
> This is wired to me as well. Since this piece of code running normally on AS 311 on my other laptop.
> 
> Can someone confirm me that this's possible to put `android.support.v4` and `androidx.core` artifacts side by side in an Android project?

No It is no possible to use both at the same time.
