### ISSUE TITLE
Bug : Multiple subscription to livedata

### ISSUE THREAD

**Issue by sagar-viradiya** [googlesamples/android-sunflower#36]
Every time you switch fragment from GardenPlantListing to PlantListing and vice versa both fragments are detached and re-attached causing **onCreateView** call. Since in onCreateView we call subscribeUi method causing **multiple live data observer**. This will lead to multiple callbacks for livedata observer and because of this multiple **notifyDataSetChanged** in adapter.

This blog post explain the issue with livedata and fragment

https://medium.com/@BladeCoder/architecture-components-pitfalls-part-1-9300dd969808

To avoid multiple observer we need to use **new view life cycle** while observing livedata instead of fragment lifecycle.

Following session from google I/O 18 will help to understand the issue better

https://youtu.be/pErTyQpA390?t=5m41s

New view life cycle is added in support lib 28.0.0 and androidx 1.0.0.

**Comment by sagar-viradiya** [comment]
@tiembo Since Android studio canary 17 is out let's switch to androidx ?
Androidx will fix this issue.

**Comment by tiembo** [comment]
@sagar-viradiya sounds good.  I have an androidx change in flight, so I'll take this issue and tag it to the pull request.

**Comment by sagar-viradiya** [comment]
@tiembo Cool

**Comment by tiembo** [comment]
Migration to androidx is blocked; will update this issue once progress resumes.

**Comment by andhie** [comment]
this can now be fixed since already upgraded to support lib v28
