### ISSUE TITLE
LifeRecycle Activity 使用异常

### ISSUE THREAD

**Issue by Vicent9920** [googlesamples/android-sunflower#366]
你好，请问在Activity中调用如下方法遇到异常：no super method get lifecycle android/life cycle/life cycle; in class android/core/apps/componentactivity; or its super classes 是什么情况啊？

`void observe(@NonNull LifecycleOwner owner, @NonNull Observer<? super T> observer)`
依赖如下：
`implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
//    implementation 'androidx.core:core-ktx:1.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0-beta01'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    // 沉浸式状态栏颜色
    implementation 'com.jaeger.statusbarutil:library:1.5.1'
    // 界面侧滑
    implementation 'cn.bingoogolapple:bga-swipebacklayout:1.2.0@aar'
    // 键对值存储器
    implementation "com.orhanobut:hawk:2.0.1"
    def nav_version = "1.0.0-rc02"
    // For Kotlin use navigation-fragment-ktx
    implementation "android.arch.navigation:navigation-fragment:$nav_version"
    // For Kotlin use navigation-ui-ktx
    implementation "android.arch.navigation:navigation-ui:$nav_version"
    def lifecycle_version = "2.0.0"
    // ViewModel and LiveData
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
//    annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"`
调用方法：
![image](https://user-images.githubusercontent.com/17283445/54084920-89476100-4372-11e9-8318-18daf6369954.png)

**Comment by shanksiscool** [comment]
for anybody wanna help, I just formatted his dependencies. Better learn markdown @Vicent9920  , check basic markdown usage [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
```bash
implementation fileTree(include: ['*.jar'], dir: 'libs') 
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" 
implementation 'androidx.appcompat:appcompat:1.0.0-beta01' 
// implementation 'androidx.core:core-ktx:1.0.1' 
implementation 'androidx.constraintlayout:constraintlayout:1.1.2' 
implementation 'androidx.legacy:legacy-support-v4:1.0.0-beta01' 
testImplementation 'junit:junit:4.12' 
androidTestImplementation 'androidx.test:runner:1.1.0-alpha4' 
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4' 

implementation 'com.squareup.retrofit2:retrofit:2.3.0' 
implementation 'com.squareup.retrofit2:converter-gson:2.3.0' // 沉浸式状态栏颜色 
implementation 'com.jaeger.statusbarutil:library:1.5.1' // 界面侧滑
implementation 'cn.bingoogolapple:bga-swipebacklayout:1.2.0@aar' // 键对值存储器 
implementation "com.orhanobut:hawk:2.0.1" def nav_version = "1.0.0-rc02" // For Kotlin use navigation-fragment-ktx 
implementation "android.arch.navigation:navigation-fragment:$nav_version" // For Kotlin use navigation-ui-ktx 
implementation "android.arch.navigation:navigation-ui:$nav_version" def lifecycle_version = "2.0.0" // ViewModel and LiveData 
implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version" 
// annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
```

**Comment by Vicent9920** [comment]
thanks
