### ISSUE TITLE
Can I implement Clean architecture?

### ISSUE THREAD

**Issue by herald25** [googlesamples/android-sunflower#373]
Can I implement Clean architecture with this repository? I want to use new technology for my future project since I started to learn more related in Android. I also want to use reacting programming with this? thanks in advance.

**Comment by XinyueZ** [comment]
The purpose of this project is not about architecture .

**Comment by nic0lette** [comment]
As @XinyueZ noted, this sample is about showing an example of how to best utilize Android Architecture Components in an app, and how one may architect it. There are many things this sample doesn't do (such as dependency injection (DI) with Dagger2).

You are free to fork this repo and build out an example of "clean architecture" with it, but, unfortunately, I don't think we'd want to take the project in that direction at the moment.
