### ISSUE TITLE
Back Navigation 

### ISSUE THREAD

**Issue by doomtrooper** [googlesamples/android-sunflower#382]
How is the `Recyclerview` position maintained on back-press, as I can see the view is re-inflated and a new `adapter` is set on coming back from `PlantDetailFragment` to `PlantListFragment`.
If someone can help here it would be much appreciated.

**Comment by dkarataiev** [comment]
LinearLayoutManager saves and restores state, you can check it by debugging following methods: onSaveInstanceState and onRestoreInstanceState.
<img width="801" alt="Screen Shot 2019-04-05 at 10 55 28 AM" src="https://user-images.githubusercontent.com/48690658/55636666-58035a80-5791-11e9-9ab1-fe855bc1c7c5.png">

**Comment by doomtrooper** [comment]
Thanks @dkarataiev I will check it out.
