### ISSUE TITLE
Fragment replace transaction without backstack entry

### ISSUE THREAD

**Issue by freaksgit** [googlesamples/android-sunflower#383]
As far as I understand, the navigation component doesn't provide opportunity to make navigation without backstack entry. The only way to do it is to create action with pop behavior. But this way provides unexpected lifecycle callbacks.

**For example:**
We have simple SplashFragment and MainFragment;
MainFragment is launched after SplashFragment;

I declared the navigation action:

```
    <action
        android:id="@+id/action_global_mainFragment"
        app:destination="@id/mainFragment"
        app:popUpTo="@+id/nav_graph" />
```

And using it for navigation from  SplashFragment to MainFragment;

**Expected callbacks sequence:**

navigate to MainFragment

```
MainFragment onAttach
MainFragment onCreate
SplashFragment onPause
SplashFragment onStop
SplashFragment onDestroyView
SplashFragment onDestroy
SplashFragment onDetach
MainFragment onViewCreated
MainFragment onStart
MainFragment onResume
```

**Actual callbacks sequence:**
navigate to MainFragment

```
MainFragment onAttach
MainFragment onCreate
MainFragment onViewCreated
MainFragment onStart
MainFragment onResume
SplashFragment onPause
SplashFragment onStop
SplashFragment onDestroyView
SplashFragment onDestroy
SplashFragment onDetach
```

Could you explain what I should do for achieving expected result?

**Comment by nic0lette** [comment]
Sorry to have to say this, but the order of callbacks under "Actual callbacks sequence" is correct.

Specifically, the new Fragment's onResume is expected to run before the old Fragment's onPause. This is consistent with the way the Activity lifecycle works.
