### ISSUE TITLE
'com.google.samples.apps.sunflower.databinding' package is still missing 

### ISSUE THREAD

**Issue by ChrisPlsn** [googlesamples/android-sunflower#390]
Same comment : https://github.com/googlesamples/android-sunflower/issues/243
Where can I get this missing package ?
Thanks 🙏

**Comment by tiembo** [comment]
See the [documentation](https://developer.android.com/topic/libraries/data-binding/start) on Data Binding to make sure your development environment is properly set up.

Closing as this is likely a configuration issue rather than with the Sunflower code itself.
