### ISSUE TITLE
Data Binding Question

### ISSUE THREAD

**Issue by iNoles** [googlesamples/android-sunflower#43]
Is it is a necessary to have kapt for databinding compiler if you are using data binding in this project?

I noticed this project doesn't have one.

**Comment by XinyueZ** [comment]
No need to declare. Since a version of gradletool it would be default. #14,#16, #27 #28 I have tried to use data binding for this project substantially.

**Comment by tiembo** [comment]
Correct - no need to declare kapt for data binding.
