### ISSUE TITLE
Can't run because type mismatch

### ISSUE THREAD

**Issue by jinjiafeng** [googlesamples/android-sunflower#465]
sunflower\app\src\main\java\com\google\samples\apps\sunflower\PlantDetailFragment.kt: (60, 50): Type mismatch: inferred type is (???) -> Unit but Observer<in Plant!> was expected

**Comment by tiembo** [comment]
I can't seem to duplicate this issue, so I'm closing this for now.  If this is still happening, please reply with a comment.
