### ISSUE TITLE
Material Design specs

### ISSUE THREAD

**Issue by andhie** [googlesamples/android-sunflower#47]
The sample app UI is quite crude, and parts of it does not follow the MD specs.
e.g. the Add icon used in the FAB is using the wrong size
e.g. paddings of text

Are there any plans to touch up the UI? or a mock that i can follow for a PR

**Comment by tiembo** [comment]
Yes, there are plans to add Material design.  Would you like to take a pass at it?

A good first PR for MD would be simply adding the dependency and changing the theme: https://material.io/develop/android/docs/getting-started/

**Comment by andhie** [comment]
sure, i'll add in the dependency, Theme.MaterialComponent, and some minor xml UI tweaks

**Comment by tiembo** [comment]
You might run into issues with implementing this.  Material Design Components require AndroidX, and there is currently an issue with AndroidX and Navigation.

**Comment by andhie** [comment]
Temporarily we can use `com.android.support:design:28.0.0-alpha3` since its the same as `com.google.android.material:material`. 
but doing so will increase the `ext {supportLibraryVersion = '28.0.0-alpha3'}`. are you fine with this?

To fully migrate to androidx, i think it should be a commit on its own.

**Comment by andhie** [comment]
There are a few things that require more touch up.

1) The spacing of the text between image and text in list item. they seems a little far, may be confusing due to the text might related to the top or the bottom image without reading the text.
suggestion 1: put the text on the image to inline it. text may need to be shorter to fit nicer
suggestion 2: have more space between the text and the next item (32dp), doing this will probably have to write a SpaceItemDecorator that applies top margin on 2nd item onwards
https://material.io/design/components/image-lists.html#anatomy

2) The image size should be in ratio. the recommended ratios are 16:9, 3:2, 4:3. the garden fragment items can be taller to support more text (e.g. 4:3 ?) while plant list can be 3:2.
https://material.io/design/layout/spacing-methods.html#containers-aspect-ratios

3) Doing transition animation to detail activity via the hero image

4) the text padding/margin in detail activity. 16dp instead of 8dp

**Comment by ankuranurag2** [comment]
The navigation drawer should close first (if open) onBackPressed. Right now, the drawer is left open while fragment transactions going in the back.

**Comment by tiembo** [comment]
@ankuranurag2 thanks for reporting that.  Can you create a new issue to track the bug separately from the this general MDC redesign issue?

**Comment by andhie** [comment]
@tiembo i think we should close this thread and open individual issues instead of delaying v0.1.3.
since MD improvements is never complete, this issue will never close .

**Comment by tiembo** [comment]
@andhie sounds good.  Closing this issue to release v0.1.3.  Mind creating new issues for the four topics you mentioned?
