### ISSUE TITLE
constraintLayoutVersion '2.0.0-beta1' is not working

### ISSUE THREAD

**Issue by praveenp317** [googlesamples/android-sunflower#486]
ConstraintLayoutVersion '2.0.0-beta1' is not working with 3.6 Canary 5 is there any specific things to be follow to use beta channel libs.

**Comment by RoarGronmo** [comment]
Here's a link for you, there is some differences between google and gradle on how they will solve this issue, just look further up in this thread.

The intermediate fix is to define the attrs our selves until they are properly defined somewehere else.

https://issuetracker.google.com/issues/136103084#comment23

RG

**Comment by tiembo** [comment]
Hi @praveenp317 - since this isn't an issue with Sunflower but rather with ConstraintLayout and Android Studio, I'm closing this issue.  @RoarGronmo has a good context link on this.

Right now Sunflower works with Android Studio 3.4 and 3.5; we haven't yet looked into using it with 3.6.
