### ISSUE TITLE
Are alfa/beta libraries best practice

### ISSUE THREAD

**Issue by jQrgen** [googlesamples/android-sunflower#489]
Hello Google

Considering project-level build.gradle where several app dependencies are stated, there are currently several jetpack libaries in beta and alfa:

```
        // App dependencies
        appCompatVersion = '1.1.0-beta01'
        constraintLayoutVersion = '2.0.0-beta1'
        .....
        fragmentVersion = '1.1.0-alpha09'
        ....
        lifecycleVersion = '2.2.0-alpha01'
        .......
        recyclerViewVersion = '1.1.0-alpha05'
       ......
```

Are these versions best practice or should I use stable? 

Why is this project using alpha and beta dependencies?

**Comment by RoarGronmo** [comment]
Of course  stable is stable, but alphaxx is often good enough, but it may
contain flaws, which may break during both build and execution. For Google
it is very valuable to report incidents if you find them. You can
"downgrade" to beta or stable if it breaks, but you may loose latest
enhancements.

RG

man. 22. jul. 2019, 19:10 skrev Jørgen Svennevik Notland <
notifications@github.com>:
