### ISSUE TITLE
Previous Activity gets recreated by UP navigation

### ISSUE THREAD

**Issue by Zhuinden** [googlesamples/android-sunflower#5]
If the previous activity exists, is it supposed to "pop up"? 

I thought according to Principles of Navigation, "if the previous destination exists on the stack, then UP should behave as BACK navigation".

> Up and Back are equivalent within your app's task
> When the system Back button would not exit your app, such as when you are on your own task and not on the start destination, the Up button should function identically to the system Back button.

**Comment by tiembo** [comment]
That's correct - this is a bug.  The Up button on the plant detail screen should behave like the Back button.

**Comment by ianhanniballake** [comment]
Also see the [related feature request](https://issuetracker.google.com/issues/79993862) on the Navigation library to have Navigation handle the activity up button as well

**Comment by Zhuinden** [comment]
If you guys ever add a pending intent that opens the detail view directly, then that up navigation won't behave as expected.

**Comment by tiembo** [comment]
Absolutely.  Adding deep links will require synthesizing a new back stack.

For more on this topic, check out https://developer.android.com/training/implementing-navigation/temporal#SynthesizeBackStack
