### ISSUE TITLE
Add "Remove plant from garden"-functionality

### ISSUE THREAD

**Issue by baalimago** [googlesamples/android-sunflower#512]
Hello! 

First of all, great repository. Helps a lot to get up to speed with android coding conventions and their best practices. 

But it seems to lack an option to remove plants from the garden. Or can't I find it?

Great stuff, thanks!

**Comment by nic0lette** [comment]
Thanks for the feedback! Removing a plant hasn't been implemented yet unfortunately.

You can follow #87 for this feature request. :)
