### ISSUE TITLE
Navigation Drawer remains open

### ISSUE THREAD

**Issue by ankuranurag2** [googlesamples/android-sunflower#54]
The navigation drawer should close first (if open) onBackPressed. Right now, the drawer is left open while fragment transactions going in the back.

**Comment by XinyueZ** [comment]
@tiembo Is it a bug to fix?

**Comment by tiembo** [comment]
@XinyueZ yes, there should be a fix for this bug.

**Comment by XinyueZ** [comment]
@tiembo I have fixed the bug in PR and added tests for it.

**Comment by XinyueZ** [comment]
Already fixed in #59

**Comment by tiembo** [comment]
Linking https://issuetracker.google.com/issues/105769977 for some additional context.
