### ISSUE TITLE
Detail page has two toolbars

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-sunflower#75]
After converting to single-activity, there're two `toolbar`s on detail screen.
The app needs a ux/ui decision what should be shown in detail page. @tiembo

**Comment by tiembo** [comment]
Good catch @XinyueZ - and indeed a good time to think about how the detail page should look.  The Session Details page in the [Google I/O 2018 Android app](https://play.google.com/store/apps/details?id=com.google.samples.apps.iosched) can serve as a good baseline of implementing a bottom app bar + FAB, along with title and details.

What are your thoughts?

**Comment by XinyueZ** [comment]
The IO app can be a benchmark for detail screen. @tiembo that's great.  I try some works to make similar effect.

**Comment by sagar-viradiya** [comment]
@tiembo and @XinyueZ Sounds good!

**Comment by andhie** [comment]
the I//O 2018 app uses a separate activity `.ui.SessionDetailActivity` to achieve it.
are there plans to revert the commit?
i think the proposed solution is by putting the AppBar in individual fragment. this helps to cater different AppBar styles.

**Comment by XinyueZ** [comment]
@andhie What's your opinion to #78 ?

**Comment by andhie** [comment]
it feels cheating. and not so elegant solution.
it sends out a wrong idea that this is how you're suppose to do it when faced with multiple AppBar situation.
at this moment, i am looking for more patterns on how to use Navigation in cases like this. e.g. different style AppBar, no AppBar.

Hopefully @ianhanniballake could shed some light on such cases.

**Comment by sagar-viradiya** [comment]
@XinyueZ Even I have similar thoughts on your changes as @andhie mentioned above. If we are sticking with single activity then we should have appbar for each fragment. Having single appbar in main activity will cause problem if you have new fragment tomorrow and it has different requirement than main activity appbar.

**Comment by XinyueZ** [comment]
@sagar-viradiya Do you agree to have appbar or toolbar on each fragment? I am not against, actually, I have worked a potential PR which based on this direction. The reason why don't select for the potential PR is that I wouldn't change base struct of all these layouts and keep simple at min changes.  @andhie How is your opinion?

**Comment by andhie** [comment]
i remember the Google I/O Navigation talk mention to put AppBar/Toolbar inside each fragment. I would wait to listen Google's opinionated guide on this.

**Comment by sagar-viradiya** [comment]
@XinyueZ I would prefer to have separate toolbar for each fragment. We need others opinion here. May be there could be better solution, but right now I could only think of this.

**Comment by XinyueZ** [comment]
@sagar-viradiya @andhie I have the alternative solution as PR #84, how about this? The approach is using toolbars for each fragment.

**Comment by sagar-viradiya** [comment]
@tiembo That would be great.

**Comment by sagar-viradiya** [comment]
@tiembo Any update ?

**Comment by XinyueZ** [comment]
@sagar-viradiya I prefer to #84

**Comment by sagar-viradiya** [comment]
@XinyueZ Will review and let you know

**Comment by XinyueZ** [comment]
@sagar-viradiya thanks,  #84 and #78 are two opposite solutions, one is multi appbar, one is single appbar, either of the two.

**Comment by tiembo** [comment]
Hi everyone - we're working on a solution for toolbars with single Activity / multiple Fragments internally.  Will update this issue once we have something to share.

@XinyueZ thanks for opening PRs #78 and #84!  It's probably a good idea to hold off on making additional commits to those for now.

**Comment by XinyueZ** [comment]
@tiembo OK, looking forward to it.

**Comment by mcastagnolo** [comment]
It looks like the NavigationComponent in alpha03 added functionality to work with implementations where fragments own their toolbars.

https://developer.android.com/jetpack/docs/release-notes#july_12_2018
https://issuetracker.google.com/issues/109868820

**Comment by XinyueZ** [comment]
I'll try it in a PR

**Comment by XinyueZ** [comment]
@tiembo

I am not sure whether it is really *logical*  to put two different scenarios and businesses together.

official [document](https://developer.android.com/topic/libraries/architecture/navigation/navigation-migrate),  at last section mentions that 
`..... In cases where multiple Activities share the same layout, the navigation graphs can be combined ....`

**Comment by sagar-viradiya** [comment]
@XinyueZ  @tiembo Any plan to address this ?

**Comment by XinyueZ** [comment]
@tiembo Please check #238, which might be a chance to fix this issue, I guess only.

**Comment by tiembo** [comment]
Hi @XinyueZ, sorry this issue and your PRs have been sitting for awhile.

Given how we will eventually add Material design to Sunflower I merged #315 as a fix for the double toolbar.  I'll go ahead and close out your PRs #78 and #84 - thank you for exploring those approaches!
