### ISSUE TITLE
getZoneForLatitude seems to have wrong checks

### ISSUE THREAD

**Issue by ndorigatti** [googlesamples/android-sunflower#8]
https://github.com/googlesamples/android-sunflower/blob/ee23fbc7608ea99a6fdd008885f0ae09d842dd47/app/src/main/java/com/google/samples/apps/sunflower/utilities/GrowZoneUtil.kt#L38
Looking at the alternatives:
    in 21.0..28.0 -> 10
    in 28.0..21.0 -> 9
    in 35.0..21.0 -> 8
    in 42.0..21.0 -> 7
    in 49.0..21.0 -> 6
    in 56.0..21.0 -> 5
    in 63.0..21.0 -> 4
    in 70.0..77.0 -> 3

35 to 21 is a subset of 42 to 21, and I'm quite sure you just made a mistake due to copy-paste, so should be:

    in 21.0..28.0 -> 10
    in 28.0..35.0 -> 9
    in 35.0..42.0 -> 8
    in 42.0..49.0 -> 7
    in 49.0..56.0 -> 6
    in 56.0..63.0 -> 5
    in 63.0..70.0 -> 4
    in 70.0..77.0 -> 3

**Comment by tiembo** [comment]
Thanks for reporting this.  We're addressing this internally.
