### ISSUE TITLE
Add Sharing to the plant detail page

### ISSUE THREAD

**Issue by tiembo** [googlesamples/android-sunflower#82]
Incorporate the [Sharing Jetpack component](https://developer.android.com/training/sharing/shareaction) to the plant detail page.

**Comment by andhie** [comment]
Are you suggesting to use `ShareActionProvider`?
What kind of share message to share?

**Comment by XinyueZ** [comment]
@tiembo same agree @andhie ,  people need wordings to share.

**Comment by tiembo** [comment]
For the sharing message, let's start with "Check out the $plant.name plant in the Android Sunflower app".

Implementation should be with `ShareCompat.IntentBuilder`
