### ISSUE TITLE
Java implementation for the same app

### ISSUE THREAD

**Issue by sanketplus** [googlesamples/android-sunflower#90]
Is there any java implementation for the same app? Or any other best-practice android sample app that is implemented in java. 

Thanks!

**Comment by tiembo** [comment]
Hi @sanketplus - currently there are no plans to implement a Java version of Sunflower.  For Android samples, check out http://developer.android.com/samples. There is also an option to filter by language.

**Comment by sanketplus** [comment]
thanks @tiembo for quick response 😇Have a great day ahead!

**Comment by hatewx** [comment]
@sanketplus @tiembo I forked android-sunflower project and translated all Koltin files to java, check out [android-sunflower-java](https://github.com/hatewx/android-sunflower-java).

> Is there any java implementation for the same app? Or any other best-practice android sample app that is implemented in java.
> 
> Thanks!

**Comment by tiembo** [comment]
@hatewx thanks for the implementation.  I added it to the [Notable Community Contributions](https://github.com/googlesamples/android-sunflower/wiki/Notable-Community-Contributions) page for those that are interested in a Java version.

**Comment by hatewx** [comment]
@tiembo Thanks a lot!

**Comment by spiderman16888** [comment]
with this java version.
after build, I can't see the detail and picture when select any plant.
unlike kt version, it can show all detail.
why google drop java developer and lack of sample code in java this case.
so angry.
I don't wanna learn kt.
please someone help to fix it in java version.

**Comment by hatewx** [comment]
@sp

> with this java version.
> after build, I can't see the detail and picture when select any plant.
> unlike kt version, it can show all detail.
> why google drop java developer and lack of sample code in java this case.
> so angry.
> I don't wanna learn kt.
> please someone help to fix it in java version.

@spiderman16888 I just saw the message today, sorry for the inconvenience. I have fixed it on [d2e8c73](https://github.com/hatewx/android-sunflower-java/commit/d2e8c73b7f680f7711eefe4afa8d2a1598c626b5), thank you for pointing it out!

**Comment by huanzhiyazi** [comment]
This is the newest version written by java, enjoy it!

[sunflower-java](https://github.com/huanzhiyazi/sunflower-java)
