### ISSUE TITLE
Use of Kotlin Android Extensions

### ISSUE THREAD

**Issue by ankuranurag2** [googlesamples/android-sunflower#93]
In GardenFragment.kt can't we directly use
 `garden_list.run{ }`
 instead of
 `findViewById<RecyclerView>(R.id.garden_list).run { }` using the Kotlin Android Extensions ?

**Comment by tiembo** [comment]
Kotlin Android Extensions can indeed replace usages of `findViewById` but this use case is not something that this project will explore.
