### ISSUE TITLE
Update ConstraintLayout to 2.0

### ISSUE THREAD

**Issue by tiembo** [googlesamples/android-sunflower#94]

**Comment by sagar-viradiya** [comment]
@tiembo Now that we are using Navigation 1.0.0-alpha4 which has fix for ConstraintLayout 2.0.0-alpha1, can we update ConstraintLayout ?

**Comment by tiembo** [comment]
@sagar-viradiya sure, we can take another look.  Would you like to open a PR?

**Comment by sagar-viradiya** [comment]
@tiembo Sure will do that.

**Comment by tiembo** [comment]
Continued in #146

**Comment by tiembo** [comment]
Closed via #145
